Repository kubernetes-sigs/krew-index, pull requests merged in 2019-06, with the labels that each got.

#157 Bump oidc-login to v1.12.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#158 Add virt.yaml for v0.17.2
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#160 virt: Adjust wording
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#161 Update virt.yaml for v0.18.1
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#164 Make corneliusweig a maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#165 fixed: install actions for bulk-actions
  plugins/bulk-action.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#166 Add who-can v0.1.0-alpha.1 plugin
  plugins/who-can.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#167 Bump the version of view-serviceaccount-kubeconfig to v2.0.2
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#168 Bump the version of open-svc to v2.1.2
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#169 Bump the version of sort-manifests to v0.2.3
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
