Repository kubernetes-sigs/krew-index, pull requests merged in 2019-11, with the labels that each got.

#295 Bump oidc-login to v1.15.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#297 Bump the version of open-svc to v2.2.0
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#298 Bump the version of view-serviceaccount-kubeconfig to v2.0.3
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#299 update plugin list
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#300 Update virt (KubeVirt virtctl plugin package) to v0.23.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#301 bump preflight and support-bundle to v0.9.11
  plugins/preflight.yaml
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#302 Bump auth-proxy to v0.5.0
  plugins/auth-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#303 Bump Outdated to 0.3.2
  plugins/outdated.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#304 Bump Support Bundle to 0.9.12
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#305 Bump preflight to 0.9.12
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#306 Bump support-bundle to 0.9.13
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#307 Krew 0.3.2
  plugins/krew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#308 Bump preflight to 0.9.13
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#311 Update plugin "access-matrix" to v0.4.2
  plugins/access-matrix.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#309 Add new plugins “ctx” and “ns”
  plugins/ctx.yaml
  plugins/ns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#312 Update plugin list
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#313 Bump grep to v1.2.1
  plugins/grep.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#314 Update ctx/ns: Add LICENSE to distribution bundle
  plugins/ctx.yaml
  plugins/ns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#316 Bump auth-proxy to v0.7.0
  plugins/auth-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#317 Bump oidc-login to v1.15.1
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#315 Add license for ca-cert and rm-standalone-pods
  plugins/ca-cert.yaml
  plugins/rm-standalone-pods.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#324 Install license for `sort-manifests`
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#339 Install license for `restart`
  plugins/restart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#318 Install license for `ssh-jump`
  plugins/ssh-jump.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#319 Install license for `custom-cols`
  plugins/custom-cols.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#320 Install license for `exec-cronjob`
  plugins/exec-cronjob.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#321 Install license for `prune-unused`
  plugins/prune-unused.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#322 Install license for `view-serviceaccount-kubeconfig`
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#323 Install license for `open-svc`
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#325 Install license for `support-bundle`
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#326 Install license for `preflight`
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#327 Install license for `outdated`
  plugins/outdated.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#328 Install license for `sudo`
  plugins/sudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#329 Install license for `gopass`
  plugins/gopass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#330 Install license for `iexec`
  plugins/iexec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#331 Install license for `warp`
  plugins/warp.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#332 Install license for `bulk-action`
  plugins/bulk-action.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#333 Install license for `view-secret`
  plugins/view-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#334 Install license for `konfig`
  plugins/konfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#335 Install license for `cssh`
  plugins/cssh.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#336 Install license for `tail`
  plugins/tail.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#337 Install license for `config-cleanup`
  plugins/config-cleanup.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#338 Install license for `who-can`
  plugins/who-can.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#340 Update plugin "get-all" to v1.2.1
  plugins/get-all.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#343 Update passman.yaml
  plugins/passman.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#342 Do not wrap `shortDescription` in view-secret
  plugins/view-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#344 Do not wrap `shortDescription` in who-can
  plugins/who-can.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#346 view-utilization release v0.3.1
  plugins/view-utilization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#294 Add plugin view-allocations 0.5.0
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#348 Add License to plugins
  plugins/exec-as.yaml
  plugins/prompt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#347 added license to zip archives
  plugins/match-name.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#352 update: plugin doctor to 0.3.0
  plugins/doctor.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#353 release new version v0.0.4 of whoami
  plugins/whoami.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#355 release new version v0.0.5 of whoami
  plugins/whoami.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#356 release new version v0.0.32 of modify-secret
  plugins/modify-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#357 release new version v0.0.3 of evict-pod
  plugins/evict-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#358 new plugin: ssm-secret
  plugins.md
  plugins/ssm-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#354 Add v0.1.0 of kubectl-snap
  plugins/snap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#360 Updated view-utilization to release v0.3.2
  plugins/view-utilization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#350 Kubectl-node-shell plugin
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#361 Update plugins list
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#362 Update OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#363 Added licence
  plugins/eksporter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#366 update view-allocations from 0.5.1 to 0.6.0
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#364 add df-pv plugin
  plugins/df-pv.yml
Labels: approved, cncf-cla: yes, lgtm, size/M
