Repository kubernetes-sigs/krew-index, pull requests merged in 2019-09, with the labels that each got.

#221 Updated to latest release-v0.3.0
  plugins/view-utilization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#220 introduces kubectl-doctor plugin to krew-index
  plugins/doctor.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#230 Update virt (KubeVirt virtctl plugin package) to v0.20.4
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#232 Increment config-cleanup plugin version
  plugins/config-cleanup.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#235 bump preflight and support-bundle to v0.9.8
  plugins/preflight.yaml
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#234 Update virt (KubeVirt virtctl plugin package) to v0.21.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#242 Bump oidc-login to v1.14.3
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#243 Bump version of krew to v0.3.0
  plugins/krew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#246 Bump grep to v1.2.0
  plugins/grep.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#249 bumpver iexec
  plugins/iexec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#251 Bump krew to v0.3.1
  plugins/krew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#250 Use latest krew for CI manifest validation
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#247 add modify-secret.yaml
  plugins/modify-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#253 Remove obsolete `head` field from manifests
  plugins/ca-cert.yaml
  plugins/exec-as.yaml
  plugins/gke-credentials.yaml
  plugins/mtail.yaml
  plugins/pod-logs.yaml
  plugins/pod-shell.yaml
  plugins/prompt.yaml
  plugins/rm-standalone-pods.yaml
  plugins/view-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#252 update release of modify-secret to v0.0.6
  plugins/modify-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#255 Bump kudo CLI to 0.7.0
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#256 Bump KUDO to 0.7.1
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#257 Bump KUDO to 0.7.2
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
