Repository kubernetes-sigs/krew-index, pull requests merged in 2019-05, with the labels that each got.

#144 Add sort-manifests plugin
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#122 Add new plugin "konfig"
  .travis.yml
  plugins/konfig.yaml
Labels: approved, cncf-cla: yes, deprecated/google-cla: yes, lgtm, size/M

#147 Bump version of plugin "konfig" to v0.2.1
  plugins/konfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#149 Bump version of oidc-login to v1.11.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#151 Bump the version of sort-manifests to v0.2.0
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#154 Bump the version of sort-manifests to v0.2.2
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#150 plugins: add tail (github.com/boz/kail)
  plugins/tail.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#155 Fix file ending of tail manifest
  plugins/tail.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#156 Add instructions to list all plugins in krew caveat section
  .github/PULL_REQUEST_TEMPLATE.md
  plugins/krew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
