Repository kubernetes-sigs/krew-index, pull requests merged in 2019-12, with the labels that each got.

#369 Improve travis configuration
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#372 Update krew version in travis CI
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#373 Bump krew to v0.3.3
  plugins/krew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#376 Upgrade exec-cronjob and prune-unused to v0.5.1
  plugins/exec-cronjob.yaml
  plugins/prune-unused.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#377 Update virt (KubeVirt virtctl plugin package) to v0.24.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#378 Adds LICENSE to krew release for fields plugin
  plugins/fields.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#375 KUDO update to 0.8.0
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#379 Adds license to fields plugin archive
  plugins/fields.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#380 adds the fleet plugin
  plugins/fleet.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#381 Update plugins list
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#382 Fix a typo in caveats of iexec
  plugins/iexec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#384 Bump grep to v1.2.2
  plugins/grep.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#388 Add plugin: pod-dive
  plugins/pod-dive.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#391 Print validated files to stderr
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#387 New plugin: capture
  plugins/capture.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#392 Bump KUDO to 0.9.0
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#393 Update virt (KubeVirt virtctl plugin package) to v0.24.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#397 bump preflight to v0.9.14
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#396 bump support-bundle to v0.9.14
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#399 update neat to v1.1.0
  plugins/neat.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#398 Add plugin: tree
  plugins.md
  plugins/tree.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#400 tree v0.1.1
  plugins/tree.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#402 Bump view-serviceaccount-kubeconfig to v2.1.1
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#403 Bump open-svc to v2.3.0
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#404 update view-allocations from 0.6.0 to 0.6.1
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#405 Update release info
  plugins/pod-dive.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
