Repository kubernetes-sigs/krew-index, pull requests merged in 2020-07, with the labels that each got.

#679 Update gadget version to 0.2.0
  plugins/gadget.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#660 Add fuzzy plugin
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#665 kyverno added
  plugins/kyverno.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#684 Add the np-viewer plugin
  plugins/np-viewer.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#685 Add the np-viewer plugin to `plugins.md`.
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#686 Add psp-util plugin
  plugins.md
  plugins/psp-util.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#693 Update virt (KubeVirt virtctl plugin package) to v0.31.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#688 bump kubetap v0.1.2
  plugins/tap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#694 Update score to v1.7.2
  plugins/score.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#637 Bump KUDO to v0.14.0
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#696 Bump KUDO to v0.15.0
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#687 Add ipick
  plugins/ipick.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#706 Bump oidc-login to v1.19.4
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#707 Bump fuzzy to v1.4.0
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#710 version update of kyverno
  plugins/kyverno.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#711 Bump schemahero to 0.10.0
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#713 Bump view_serviceaccount_kubeconfig to v2.2.1
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#714 Bump open-svc to v2.4.1
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#715 Bump fuzzy to v1.5.0
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#691 Add split-yaml plugin
  plugins/split-yaml.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#709 Add cert-manager kubectl plugin to index
  plugins/cert-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#719 Bump fuzzy to v1.5.1
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#720 View Utilization Release v0.3.3
  plugins/view-utilization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#724 Update cert-manager plugin to v0.16.0
  plugins/cert-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#726 Update view-secrets to v0.6.0
  plugins/view-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#718 add emit-event plugin
  plugins/emit-event.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#728 Bump schemahero to v0.10.1
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#729 Schemahero 0.10.2
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#727 Add datadog plugin to index
  plugins.md
  plugins/datadog.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#733 Update score to v1.7.3
  plugins/score.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#736 Schemahero 0.10.3
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
