Repository kubernetes-sigs/krew-index, pull requests merged in 2020-05, with the labels that each got.

#596 Bump sort-manifests to v0.4.0
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#601 Update virt (KubeVirt virtctl plugin package) to v0.29.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#600 Kuttl v0.2.0
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#602 rbac-view updates
  plugins/rbac-view.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#603 update view-allocations from 0.7.0 to 0.7.2
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#604 update install link
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#607 preflight v0.9.32
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, size/S

#606 support-bundle v0.9.32
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#610 Update score to v1.7.0
  plugins/score.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#611 KUDO 0.13.0 Bump
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#612 KUTTL 0.2.1 Bump
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#613 Update ssh-jump.yaml for v0.3.2
  plugins/ssh-jump.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#605 Eksporter v1.3.0 release
  plugins/eksporter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#614 Bump oidc-login to v1.19.1
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#620 release new version v0.1.0 of tmux-exec
  plugins/tmux-exec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#562 new plugin: roll
  plugins/roll.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#621 Update: kubectl-images release new verion v.0.2.0
  plugins/images.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#622 Bump auth-proxy to v1.0.1
  plugins/auth-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#630 bump kubectl-neat to v1.2.0
  plugins/neat.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#628 Add gadget plugin
  plugins/gadget.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#633 add podevents plugin
  plugins/podevents.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#623 kubetap submission
  plugins/tap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#632 add sick-pods plugin
  plugins/sick-pods.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#627 Add SchemaHero to krew index
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#634 gadget: Update description
  plugins/gadget.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
