Repository kubernetes-sigs/krew-index, pull requests merged in 2020-10, with the labels that each got.

#845 Bump fuzzy to v1.7.0
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#854 Update to latest kubectl-minio release
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#855 new version v1.2.3 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#856 release new version v1.2.0 of kyverno
  plugins/kyverno.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#858 Update virt (KubeVirt virtctl plugin package) to v0.34.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#860 bump kubectl-fuzzy to v1.8.0
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#862 Bump KUDO to version 0.17
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#870 Update ssh-jump.yaml for v0.5.0
  plugins/ssh-jump.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#869 add kubectl view-cert plugin
  plugins/view-cert.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#871 Add kubectl allctx plugin
  plugins/allctx.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#873 Bump KUDO to version 0.17.1
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#878 Upgrade kubectl-images version to v0.3.1
  plugins/images.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#881 Update tree manifest (remove defaults)
  plugins/tree.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#882 Redirect plugin list to the site
  README.md
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#857 Add kubectl-config-registry plugin
  plugins/config-registry.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#883 Add shovel plugin
  plugins/shovel.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#889 Remove travis
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#888 KUTTL Bump 0.7.1
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#890 Update HNS plugin to v0.6.0
  plugins/hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#886 add kubectl-creyaml plugin
  plugins/creyaml.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
