Repository kubernetes-sigs/krew-index, pull requests merged in 2020-12, with the labels that each got.

#958 Update HNS plugin to v0.7
  plugins/hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#959 Upgrade kubectl-images version to v0.3.2
  plugins/images.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#962 Fix kubectl-virt-plugin homepage
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#964 Add myself to owners alias
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#961 Add kubectl-hlf plugin
  plugins/hlf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#968 add janitor plugin v0.1.0
  plugins/janitor.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
