Repository kubernetes-sigs/krew-index, pull requests merged in 2020-11, with the labels that each got.

#893 update view-allocations from 0.8.2 to 0.9.1
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#894 bump to kuttl 0.7.2
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#896 update view-allocations from 0.9.1 to 0.9.2
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#897 Update score to v1.10.0
  plugins/score.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#902 Bump the version of open-svc to v2.4.2
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#903 Bump the version of sort-manifests to v0.4.1
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#895 Add rabbitmq
  plugins/rabbitmq.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#905 Bump oidc-login to v1.22.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#906 Bump rabbitmq
  plugins/rabbitmq.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#910 Add new view-webhook plugin
  plugins/view-webhook.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#923 KUDO 0.17.2 Bump
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#924 bump fuzzy to v1.8.1
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#925 bump kail to 0.15.0
  plugins/tail.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#931 new version v3.0.29 of kubectl-minio
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#932 release new version v0.2.0 of tmux-exec
  plugins/tmux-exec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#936 schemahero v0.11.3
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
