Repository kubernetes-sigs/krew-index, pull requests merged in 2020-06, with the labels that each got.

#629 Add service-tree plugin
  plugins/service-tree.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#636 Update plugins.md to include newest plugins
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#638 Bump KUTTL 0.4.0
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#635 Remove redundant information from `caveats`
  plugins/bulk-action.yaml
  plugins/change-ns.yaml
  plugins/deprecations.yaml
  plugins/exec-cronjob.yaml
  plugins/fields.yaml
  plugins/fleet.yaml
  plugins/grep.yaml
  plugins/iexec.yaml
  plugins/konfig.yaml
  plugins/krew.yaml
  plugins/kubesec-scan.yaml
  plugins/kudo.yaml
  plugins/kuttl.yaml
  plugins/modify-secret.yaml
  plugins/node-shell.yaml
  plugins/ns.yaml
  plugins/oidc-login.yaml
  plugins/outdated.yaml
  plugins/passman.yaml
  plugins/preflight.yaml
  plugins/prompt.yaml
  plugins/prune-unused.yaml
  plugins/rbac-view.yaml
  plugins/schemahero.yaml
  plugins/snap.yaml
  plugins/ssm-secret.yaml
  plugins/status.yaml
  plugins/support-bundle.yaml
  plugins/tail.yaml
  plugins/virt.yaml
  plugins/warp.yaml
  plugins/who-can.yaml
  plugins/whoami.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#642 Bump SchemaHero to 0.9.0
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#645 Bump oidc-login to v1.19.2
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#641 Update virt (KubeVirt virtctl plugin package) to v0.30.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#648 update view-allocations from 0.7.2 to 0.7.3
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#647 adding starboard plugin
  plugins/starboard.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#656 version v0.0.4 for custom-cols
  plugins/custom-cols.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#657 Upgrade kubectl-images version to v0.3.0
  plugins/images.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#644 added openunison login plugin
  plugins/oulogin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#659 new version v1.1.0 of deprecations
  plugins/deprecations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#655 bulk-action plugin updated
  plugins/bulk-action.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#663 chore: updating starboard to v0.2.2
  plugins/starboard.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#664 Bump oidc-login to v1.19.3
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#643 Add sample plugin
  plugins/example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#666 Update naming guide URL in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#672 upgrade custom-cols to v0.0.5
  plugins/custom-cols.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#667 Add gs plugin
  plugins.md
  plugins/gs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#676 release new version v0.1.1 of tmux-exec
  plugins/tmux-exec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#658 Add kubectl trace v0.1.0-rc.1
  plugins.md
  plugins/trace.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
