Repository kubernetes-sigs/krew-index, pull requests merged in 2020-03, with the labels that each got.

#517 Add kube-score to index
  plugins.md
  plugins/score.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#519 Bump outdated to 0.3.3
  plugins/outdated.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#521 Adding popeye to the krew...
  plugins/popeye.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#524 Bump preflight to v0.9.24
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#525 Bump version to v0.9.24
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#523 Add tmux-exec to index
  plugins.md
  plugins/tmux-exec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#529 update plugins.md
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#530 Update virt (KubeVirt virtctl plugin package) to v0.27.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#533 Update virt (KubeVirt virtctl plugin package) to v0.27.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#534 Bump support-bundle version to v0.9.26
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#535 Bump preflight to v0.9.26
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#526 Add resource-status
  plugins/status.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#532 Add sql plugin
  plugins/sql.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#542 new version v1.1.1 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#544 release new version v0.0.4 of tmux-exec
  plugins/tmux-exec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#547 updating kudo to 0.11.0
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#548 Update developer guide link and slack channel name in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#549 Update view-secrets to v0.5.0
  plugins/view-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#546 Add rolesum(ex-bindrole) plugin to index
  plugins/rolesum.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#550 Bump 'kubectl-topology' to v0.1.1.
  plugins/topology.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#551 bump kudo to 0.11.1
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#552 Small improvement to get the deployment name
  plugins/resource-snapshot.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#554 Bump oidc-login to v1.18.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#555 update preflight to v0.9.28
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#556 update support bundle to v0.9.28
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#558 bump node-restart to v1.0.0
  plugins/node-restart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#561 new version v1.1.2 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
