Repository kubernetes-sigs/krew-index, pull requests merged in 2020-01, with the labels that each got.

#408 fix 404 url
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#407 updates fleet plugin
  plugins/fleet.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#409 update view-allocations from 0.6.1 to 0.6.2
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#410 tree v0.2.0
  plugins/tree.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#406 Add Snapshot plugin
  plugins/resource-snapshot.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#417 bump preflight to v0.9.15
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#418 bump support-bundle to v0.9.15
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#420 bump preflight to v0.9.16
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#421 bump support-bundle to v0.9.16
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#401 add spy plugin
  plugins/spy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#422 Update plugin "get-all" to v1.3.0
  plugins/get-all.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#423 bump support-bundle to v0.9.17
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#424 bump preflight to v0.9.17
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#425 Bump KUDO to v0.10.0
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#426 chore: Update mtail to 1.2.0 and add LICENSE file
  plugins/mtail.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#419 Update plugins list
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#434 Update virt (KubeVirt virtctl plugin package) to v0.25.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#415 Add profefe plugin
  plugins.md
  plugins/profefe.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#428 adding kubectl duck to krew index.
  plugins/duck.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#439 add plugin: advise-psp (kube-psp-advisor)
  plugins/advise-psp.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#438 Add kubepug (kubectl deprecations)
  plugins/deprecations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#442 new plugin: net-forward
  plugins/net-forward.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#448 Update support-bundle to v0.9.18
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#447 Update preflight to v0.9.18
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#450 Update support-bundle to 0.9.19
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#451 Update preflight to 0.9.19
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#449 Bump oidc-login to v1.15.2
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#453 Bump auth-proxy to v1.0.0
  plugins/auth-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#454 Bump sort-manifests to v0.3.0
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#452 bump spy to v0.3.3
  plugins/spy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#455 Bump oidc-login to v1.16.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#458 Update support-bundle to 0.9.20
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#459 Update preflight to 0.9.20
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#437 Migrate to GitHub workflows for CI
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#460 update plugins list
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#467 Bump support-bundle to v0.9.21
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#468 Bump preflight version to v0.9.21
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
