Repository kubernetes-sigs/krew-index, pull requests merged in 2020-04, with the labels that each got.

#559 Add 'kubectl-cilium'.
  plugins/cilium.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#564 Introduce new krew plugin apparmor-manager
  plugins/apparmor-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#565 update neat to v1.1.1
  plugins/neat.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#570 Bump 'kubectl-cilium' to v0.1.1.
  plugins/cilium.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#572 chore: Bump up who-can to v0.1.1
  plugins/who-can.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#573 Bump oidc-login to v1.19.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#574 Update virt (KubeVirt virtctl plugin package) to v0.28.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#576 kudo v0.12.0 bump
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#578 Update ssh-jump.yaml for v0.3.1
  plugins/ssh-jump.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#579 Update score to v1.6.0
  plugins/score.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#581 Change my username + update 'plugins.md'.
  plugins.md
  plugins/cilium.yaml
  plugins/topology.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#582 new version v1.1.3 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#583 new version v1.1.4 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#584 preflight v0.9.29
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#585 support-bundle v0.9.29
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#587 preflight v0.9.30
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#586 support-bundle v0.9.30
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#588 Update ingress-nginx plugin
  plugins/ingress-nginx.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#589 Bump the version of open-svc to v2.4.0
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#590 Bump the version of view-serviceaccount-kubeconfig to v2.2.0
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#591 update support-bundle to v0.9.31
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#592 update preflight to v0.9.31
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
