Repository kubernetes-sigs/krew-index, pull requests merged in 2020-08, with the labels that each got.

#739 bump kubectl-neat to v2.0.0
  plugins/neat.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#740 Bump oidc-login to v1.20.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#745 Update ssh-jump.yaml for v0.4.0
  plugins/ssh-jump.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#747 Bump fuzzy to v1.5.2
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#746 bump kubectl-neat to v2.0.1
  plugins/neat.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#737 Add operator plugin
  plugins/operator.yaml
Labels: approved, cncf-cla: yes, kind/gray-area, lgtm, size/M

#748 schemahero v0.10.4
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#750 Bump grep to v1.2.6
  plugins/grep.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#751 Update score to v1.8.0
  plugins/score.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#753 Update score to v1.8.1
  plugins/score.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#758 Bump auth-proxy to v1.1.0
  plugins/auth-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#760 adding support for mac for net-forward plugin
  plugins/net-forward.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#763 Update virt (KubeVirt virtctl plugin package) to v0.32.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#765 update view-allocations from 0.7.3 to 0.8.2
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#772 bump node-restart v1.0.1
  plugins/node-restart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#774 Release krew v0.4.0
  plugins/krew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#773 Add plugin graph to the krew-index
  plugins/graph.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#784 new version v1.2.0 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#787 Bump KUDO to version 0.16
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#788 Update datadog plugin
  plugins/datadog.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#790 new version v1.2.1 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
