Repository kubernetes-sigs/krew-index, pull requests merged in 2020-02, with the labels that each got.

#471 new version v1.0.1 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#474 Update view-secret to v0.4.0
  plugins/view-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#462 Add new plugin - `kubectl sshd`
  plugins/sshd.yaml
Labels: cncf-cla: yes, kind/gray-area, lgtm, size/M

#479 new version v1.1.0 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#480 Bump SupportBundle to 0.9.22
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#481 Bump Preflight to 0.9.22
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#475 Add plugin: cluster-group
  plugins/cluster-group.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#476 add if statement for pr & push event
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#484 update view-allocations from 0.6.2 to 0.7.0
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#489 update owner org to kubectl-plus
  plugins/fleet.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#491 Update virt (KubeVirt virtctl plugin package) to v0.26.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#486 Fix manifest validation in GitHub actions pipeline
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#493 Bump oidc-login to v1.17.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#494 Release krew v0.3.4
  plugins/krew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#498 Update gopass plugin to version 0.1.1
  plugins/gopass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#497 Add 'kubectl-topology'.
  plugins/topology.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#495 Update krew version to be used in CI
  .github/workflows/ci.yml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#500 Update 'plugins.md'.
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#501 Add plugin: kubectl-image
  plugins/images.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#499 add plugin: kubectl node-restart
  plugins/node-restart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#504 chore(who-can): Bump up to v0.1.0
  plugins/who-can.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#508 Bump oidc-login to v1.17.1
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#512 Update: plugins.md
  plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#514 bump preflight to v0.9.23
  plugins/preflight.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#513 bump support-bundle to v0.9.23
  plugins/support-bundle.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#515 Bump sort-manifests to v0.3.1
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
