Repository kubernetes-sigs/krew-index, pull requests merged in 2020-09, with the labels that each got.

#786 add bd-xray plugin
  plugins/bd-xray.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#798 new version v1.2.2 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#800 Upgrade cert-manager to 1.0.1
  plugins/cert-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#802 Bump oidc-login to v1.20.1
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#797 Bump versions in CI scripts
  .github/workflows/ci.yml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#791 Add plugin: edit-status
  plugins/edit-status.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#812 Bump fuzzy to v1.6.0
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#818 Update virt (KubeVirt virtctl plugin package) to v0.33.0
  plugins/virt.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#819 Bump SchemaHero to 0.11.0
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#820 Bump SchemaHero to 0.11.1
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#815 Add kubectl-minio plugin
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#822 Bump the version of view-serviceaccount-kubeconfig to v2.2.2
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#793 Add reap plugin
  plugins/reap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#825 Bump konfig to v0.2.3
  plugins/konfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#827 schemahero v0.11.2
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#830 Bump oidc-login to v1.21.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#831 Bump the version of view-serviceaccount-kubeconfig to v2.2.3
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#828 Add HNS plugin
  plugins.md
  plugins/hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#832 Update score to v1.9.0
  plugins/score.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#837 bump fuzzy version to v1.6.1
  plugins/fuzzy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#838 Upgrade HNS to v0.5.3 final
  plugins/hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
