Repository kubernetes-sigs/krew-index, pull requests merged in 2021-06, with the labels that each got.

#1314 [minio/direct-csi] Update version to v1.3.5
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1317 [minio/direct-csi] Update version to v1.3.6
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1318 Adds darwin support for whisper-secret
  plugins/whisper-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1322 update to v4.1.1 release
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1330 new version v0.14.1 of view-allocations
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1331 HLF v1.2.1
  plugins/hlf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1332 new version v1.4.0 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1333 Create karbon.yaml
  plugins/karbon.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1344 Update MinIO plugin to release 4.1.2
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
