Repository kubernetes-sigs/krew-index, pull requests merged in 2021-01, with the labels that each got.

#973 release new version v0.3.0 of tmux-exec
  plugins/tmux-exec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#976 bump kubectl-neat to v2.0.2
  plugins/neat.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#977 Add deprecation notice to debug plugin
  plugins/debug.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#967 [minio/direct-csi] add kubectl-direct_csi plugin v1.0.0
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#983 minor upgrade with better context management
  plugins/oulogin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#984 fix version string in bin
  plugins/oulogin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#985 bump to kuttl 0.8.0
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#989 New version v1.3.0 of kyverno
  plugins/kyverno.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#991 add kubectl-skew plugin
  plugins/skew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#993 Remove tee line that's causing errors in ci
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#990 New version v1.3.1 of Kyverno
  plugins/kyverno.yaml
Labels: cncf-cla: yes, size/S

#994 Revert "Remove tee line that's causing errors in ci"
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#997 Add azad-proxy to krew-index
  plugins/azad-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#999 azad-proxy: Update homepage to correct casing
  plugins/azad-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1004 [minio/direct-csi] Update version to v1.1.0 and windows/darwin support
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#995 New plugin - socks5-proxy
  plugins/socks5-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#981 Added new plugin flyte [flyte.org]
  plugins/flyte.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
