Repository kubernetes-sigs/krew-index, pull requests merged in 2021-07, with the labels that each got.

#1376 add new plugin pvmigrate
  plugins/pvmigrate.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1378 Update MinIO to 4.1.3 release
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1382 new version v1.5.0 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1385 new version v1.5.1 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1395 new version v1.5.2 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1398 new version v1.5.3 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1404 bump kuttl to 0.11.0
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1405 Adding Darwin M1 Arm 64 support
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1392 Add rbac-tool krew plugin
  plugins/rbac-tool.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1418 schemahero v0.12.3
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1424 [minio/direct-csi] Update version to v1.4.0
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1433 Update `datadog` plugin to `v0.6.0`
  plugins/datadog.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
