Repository kubernetes-sigs/krew-index, pull requests merged in 2021-03, with the labels that each got.

#1082 [minio/direct-csi] Update version to v1.2.7
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1089 update minio plugin to v4.0.1 release
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1083 release new version v0.5.0 of reliably
  plugins/reliably.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1091 [minio/direct-csi] Update version to v1.2.8
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1063 add plugin pod-lens
  plugins/pod-lens.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1092 update minio plugin to v4.0.2 release
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1088 Adds kubectl-ccsecret plugin file
  plugins/whisper-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1104 HLF V1.1.0
  plugins/hlf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1093 Add kubectl-assert plugin file
  plugins/assert.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1112 Upgrade kubectl-images version to v0.3.3
  plugins/images.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1115 Update pod-inspect to 0.1.8
  plugins/pod-inspect.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1129 Bump SchemaHero to 0.12.0
  plugins/schemahero.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1146 Update oidc-login to v1.23.0
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1155 update minio plugin to v4.0.4 release
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1136 Add kpexec
  plugins/kpexec.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1159 new version v1.2.5 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
