Repository kubernetes-sigs/krew-index, pull requests merged in 2021-05, with the labels that each got.

#1256 Bump the version of open-svc to v2.4.4
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1252 Upgrade HNS plugin to v0.8.0
  plugins/hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1257 Bump the version of view-serviceaccount-kubeconfig to v2.2.6
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1258 new version v0.2.0 of edit-status
  plugins/edit-status.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1233 Update kube-capacity to v0.6.0
  plugins/resource-capacity.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1194 update view-allocations from 0.12.1 to 0.13.1
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1266 new version v0.1.2 of cilium
  plugins/cilium.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1259 Add promdump plugin
  plugins/promdump.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1272 Bump the version of open-svc to v2.5.0
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1273 Bump the version of sort-manifests to v0.4.2
  plugins/sort-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1278 Update kubectl-sudo from v1.0.1 to v1.1.0
  plugins/sudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1279 new version v1.3.0 of node-shell
  plugins/node-shell.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1277 KUDO 0.19.0 Bump
  plugins/kudo.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1280 added tunnel plugin to krew
  plugins/tunnel.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1293 KUTTL 0.10.0 Bump
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1295 [minio/direct-csi] Update version to v1.3.4
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1298 Update to MinIO Operator v4.0.11
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1300 release new version v1.0.2 of node-restart
  plugins/node-restart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1310 Update to MinIO Operator release 4.1.0
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
