Repository kubernetes-sigs/krew-index, pull requests merged in 2021-11, with the labels that each got.

#1619 Plugin added: karmada-cli
  plugins/karmada.yaml
Labels: size/M, cncf-cla: yes, lgtm, approved

#1720 update minio to v4.3.2
  plugins/minio.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1724 Update cert-manager kubectl plugin to 1.6.1
  plugins/cert-manager.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1725 update minio to v4.3.3
  plugins/minio.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1730 update direct-csi v1.4.4
  plugins/direct-csi.yaml
Labels: size/M, cncf-cla: yes, lgtm, approved

#1735 update minio to v4.3.4
  plugins/minio.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1732 Add kubectl-strace plugin to krew index
  plugins/strace.yaml
Labels: size/M, cncf-cla: yes, lgtm, approved

#1748 MinIO v4.3.5
  plugins/minio.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1738 Add 'kubectl-kadalu' plugin
  plugins/kadalu.yaml
Labels: size/M, cncf-cla: yes, lgtm, approved

#1753 new version v0.6.1 of viewnode
  plugins/viewnode.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1762 fix for homepage of viewnode
  plugins/viewnode.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1721 Add kubectl-moco plugin to krew index
  plugins/moco.yaml
Labels: size/M, cncf-cla: yes, lgtm, approved

#1776 update karmada CLI to v0.10.0
  plugins/karmada.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1779 add new version v0.7.0 of viewnode
  plugins/viewnode.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1726 Add kubectl-accurate plugin to krew index
  plugins/accurate.yaml
Labels: size/M, cncf-cla: yes, lgtm, approved

#1782 [minio/direct-csi] Update version to v1.4.6
  plugins/direct-csi.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved
