Repository kubernetes-sigs/krew-index, pull requests merged in 2021-02, with the labels that each got.

#1007 [minio/direct-csi] Update version to v1.2.0
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1009 Update flytectl homepage
  plugins/flyte.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1012 update view-allocatrions from 0.9.2 to 0.11.0
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1013 [minio/direct-csi] upgrade to v1.2.1
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1016 [minio/direct-csi] Update version to v1.2.2
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1023 bump oulogin plugin
  plugins/oulogin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1021 added plugin pod-inspect
  plugins/pod-inspect.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1032 [minio/direct-csi] Update version to v1.2.4
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1039 Bump the version of oidc-login to v1.22.1
  plugins/oidc-login.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1037 Upgrade cert-manager to 1.2.0
  plugins/cert-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1041 Update validate-krew-manifest
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1042 new version v0.2.0 of operator
  plugins/operator.yaml
Labels: cncf-cla: yes, size/S

#1043 krew v0.4.1
  .github/workflows/ci.yml
  plugins/krew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1044 update view-allocations from 0.11.0 to 0.12.1
  plugins/view-allocations.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1045 [minio/direct-csi] Update version to v1.2.5
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1046 Bump the version of open-svc to v2.4.3
  plugins/open-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1022 Add Reliably plugin
  plugins/reliably.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1003 Add new plugin kubectl-mc, a multi cluster kubectl client
  plugins/mc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1026 add kubectl cyclonus plugin
  plugins/cyclonus.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1051 [minio/direct-csi] bump version to v1.2.6
  plugins/direct-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1057 update minio.yaml to latest release v4.0.0
  plugins/minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1067 update to 0.0.7
  plugins/oulogin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1073 bump kuttl to 0.9.0
  plugins/kuttl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1076 Bump auth-proxy to v1.1.1
  plugins/auth-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
