Repository kubernetes-sigs/krew-index, pull requests merged in 2021-08, with the labels that each got.

#1448 Bump the version of open-svc to v2.5.1
  plugins/open-svc.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1449 Bump the version of view-serviceaccount-kubeconfig to v2.2.7
  plugins/view-serviceaccount-kubeconfig.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1450 KUTTL 0.11.1 Bump
  plugins/kuttl.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1455 feat: add plugin kubectl-blame
  plugins/blame.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1459 Update Kyverno CLI to 1.4.2
  plugins/kyverno.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1460 Add openebs plugin to krew index
  plugins/openebs.yaml
Labels: size/M, cncf-cla: yes, lgtm

#1463 Update socks5-proxy.yaml for v1.0.2
  plugins/socks5-proxy.yaml
Labels: size/XS, cncf-cla: yes, lgtm, approved

#1465 [minio/direct-csi] Update version to v1.4.1
  plugins/direct-csi.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1470 Release new version v0.1.2 of resource-versions
  plugins/resource-versions.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1468 Update openebs plugin
  plugins/openebs.yaml
Labels: size/M, cncf-cla: yes, lgtm, approved

#1480 update minio-operator release v4.2.0
  plugins/minio.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1484 update minio.yaml v4.2.2
  plugins/minio.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#1454 add Clusternet plugin
  plugins/clusternet.yaml
Labels: size/M, cncf-cla: yes, lgtm, approved

#1494 Update minio.yaml to v4.2.3
  plugins/minio.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved
